### ISSUE TITLE
How to install Newt in conda virtual environment?

### ISSUE THREAD

**Issue by mohammad-saber** [AaltoML/Newt#1]
Hi, thank you for sharing your great work.

I am a little confused about how to install Newt in a conda VE. I really appreciate it if you could guide in this regard. Thank you

**Comment by wil-j-wil** [comment]
Hi,
I haven't tried in a conda virtual environment myself. But I guess it should work if you clone this git repo, and then whilst running your virtual environment run
`pip install -e .`
in the top (Newt) directory.
Let me know if it doesn't work.

**Comment by mohammad-saber** [comment]
Thank you. It works.
